include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = GraphConfiguration

GraphConfiguration_PRINCIPAL_CLASS = GraphConfiguration
GraphConfiguration_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
GraphConfiguration_RESOURCE_FILES = \
				GraphConfiguration.gsmarkup \
				GraphConfiguration.plist
GraphConfiguration_OBJC_FILES = \
				GraphConfiguration.m \
				GraphConfiguration+Interface.m \
				GraphConfiguration+Protocol.m
GraphConfiguration_GUI_LIBS = -lRenaissance

include $(GNUSTEP_MAKEFILES)/bundle.make
