include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = TimeIntegration

TimeIntegration_PRINCIPAL_CLASS = TimeIntegration
TimeIntegration_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
TimeIntegration_OBJC_FILES = TimeIntegration.m

include $(GNUSTEP_MAKEFILES)/bundle.make
