include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = TimeInterval

TimeInterval_PRINCIPAL_CLASS = TimeInterval
TimeInterval_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
TimeInterval_RESOURCE_FILES = TimeInterval.gsmarkup TimeInterval.plist
TimeInterval_OBJC_FILES = TimeInterval.m SliceView.m
TimeInterval_GUI_LIBS = -lRenaissance

include $(GNUSTEP_MAKEFILES)/bundle.make
