#ifndef __TimeIntervalWindow__
#define __TimeIntervalWindow__

/**
@file
Subclass of TimeIntervalWindowAuto, which is generated by wxFormBuilder.
*/

#include "TimeIntervalWindowAuto.h"
#include <Foundation/Foundation.h>
#include <General/PajeFilter.h>
#include "TimeInterval.h"


/** Implementing TimeIntervalWindowAuto */
class TimeIntervalWindow : public TimeIntervalWindowAuto
{
private:
	id filter;
public:
	/** Constructor */
	TimeIntervalWindow( wxWindow* parent );
	void setController (id contr) { filter = contr; };
	void setTraceStartTime (wxString str);
	void setTraceEndTime (wxString str);
	void setSelectionStartTime (wxString str);
	void setSelectionEndTime (wxString str);
	void setSlidersRange (int start, int end);

protected:
	void startScroll( wxScrollEvent& event );
	void endScroll( wxScrollEvent& event );
	void apply( wxCommandEvent& event );
};

#endif // __TimeIntervalWindow__
