#ifndef __TimeIntervalWindow__
#define __TimeIntervalWindow__

/**
@file
Subclass of TimeIntervalWindowAuto, which is generated by wxFormBuilder.
*/

#include "TimeIntervalWindowAuto.h"
#include <Foundation/Foundation.h>
#include <General/PajeFilter.h>
#include "TimeInterval.h"
#include <wx/wxprec.h>
#include <wx/wx.h>


/** Implementing TimeIntervalWindowAuto */
class TimeIntervalWindow : public TimeIntervalWindowAuto
{
private:
	id filter;
	double timeStep;
	void updateText ();
public:
	/** Constructor */
	TimeIntervalWindow( wxWindow* parent );
	void setController (id contr) { filter = contr; };
	SliceDraw *getSliceDraw () { return sliceDraw; };
	void animate (wxTimerEvent& event);

protected:
	void sliderChanged( wxScrollEvent& event );
	void animationSliderChanged( wxScrollEvent& event );
	void preciseSliceEntered( wxCommandEvent& event );
	void apply( wxCommandEvent& event );
	void play( wxCommandEvent& event );
	void pause( wxCommandEvent& event );
};

#endif // __TimeIntervalWindow__
