#ifndef __TimeIntervalWindow__
#define __TimeIntervalWindow__

/**
@file
Subclass of TimeIntervalWindowAuto, which is generated by wxFormBuilder.
*/

#include "TimeIntervalWindowAuto.h"
#include <Foundation/Foundation.h>
#include <General/PajeFilter.h>
#include "TimeInterval.h"
#include <wx/wxprec.h>
#include <wx/wx.h>


/** Implementing TimeIntervalWindowAuto */
class TimeIntervalWindow : public TimeIntervalWindowAuto
{
private:
	id filter;
	wxTimer playTimer;
	double timeStep;
	void updateText ();
public:
	/** Constructor */
	TimeIntervalWindow( wxWindow* parent );
	void setController (id contr) { filter = contr; };
	void setTraceStartTime (wxString str);
	void setTraceEndTime (wxString str);
	void setSelectionStartTime (wxString str);
	void setSelectionEndTime (wxString str);
	void setSlidersRange (int start, int end);
	void setSlidersValue (int start, int end);

	void forwardTime (wxTimerEvent& event);
protected:
	void startScroll( wxScrollEvent& event );
	void endScroll( wxScrollEvent& event );
	void apply( wxCommandEvent& event );
	void play( wxCommandEvent& event );
};

#endif // __TimeIntervalWindow__
