include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = StatTrace

StatTrace_PRINCIPAL_CLASS = StatTrace
StatTrace_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
StatTrace_OBJC_FILES = StatTrace.m

include $(GNUSTEP_MAKEFILES)/bundle.make
