#ifndef __OgreWindow__
#define __OgreWindow__

/**
@file
Subclass of OgreWindowAuto, which is generated by wxFormBuilder.
*/

#include "OgreWindowAuto.h"
#include "CameraManager.h"
#include "AmbientManager.h"

/** Implementing OgreWindowAuto */
class OgreWindow : public OgreWindowAuto
{
private:
	id filter;
	CameraManager *cameraManager;
	AmbientManager *ambientManager;
public:
	/** Constructor */
	OgreWindow( wxWindow* parent );
	~OgreWindow ();
	void zoomIn();
	void zoomOut();
	void setController (id f) { filter = f; };
	void configureZoom (double pointsPerSec);
};

#endif // __OgreWindow__
