#ifndef __MAWindow__
#define __MAWindow__

/**
@file
Subclass of MAWindowAuto, which is generated by wxFormBuilder.
*/

#include "MAWindowAuto.h"
#include "MADraw.h"

/** Implementing MAWindowAuto */
class MAWindow : public MAWindowAuto
{
public:
	/** Constructor */
	MAWindow( wxWindow* parent );
	MADraw *getMADraw () { return mDraw; }
};

#endif // __MAWindow__
