include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = GraphView

GraphView_PRINCIPAL_CLASS = GraphView
GraphView_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
GraphView_RESOURCE_FILES = GraphView.gsmarkup GraphView.plist
GraphView_OBJC_FILES = GraphView.m DrawView.m GraphNode.m
GraphView_GUI_LIBS = -lRenaissance -lTupi

include $(GNUSTEP_MAKEFILES)/bundle.make
