include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = GraphView

GraphView_PRINCIPAL_CLASS = GraphView
GraphView_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
GraphView_RESOURCE_FILES = GraphView.gsmarkup GraphView.plist
GraphView_OBJC_FILES = DrawView.m GraphView.m
GraphView_GUI_LIBS = -lRenaissance

include $(GNUSTEP_MAKEFILES)/bundle.make
