#ifndef __GraphWindow__
#define __GraphWindow__

/**
@file
Subclass of GraphWindowAuto, which is generated by wxFormBuilder.
*/

#include "GraphWindowAuto.h"
#include "GraphDraw.h"

/** Implementing GraphWindowAuto */
class GraphWindow : public GraphWindowAuto
{
public:
	/** Constructor */
	GraphWindow( wxWindow* parent );
        GraphDraw *getDraw();
	void setStatusMessage (wxString message);
};

#endif // __GraphWindow__
