#ifndef __NUCAWindow__
#define __NUCAWindow__

/**
@file
Subclass of NUCAWindowAuto, which is generated by wxFormBuilder.
*/

#include "NUCAWindowAuto.h"
#include "NUCADraw.h"

/** Implementing NUCAWindowAuto */
class NUCAWindow : public NUCAWindowAuto
{
public:
	/** Constructor */
	NUCAWindow( wxWindow* parent );
        NUCADraw *getDraw();
	void setStatusMessage (wxString message);
};

#endif // __NUCAWindow__
