#ifndef __GUI_COMBINEDCOUNTER_H__
#define __GUI_COMBINEDCOUNTER_H__

#include "TrivaAutoGeneratedGUI.h"
#include "gui/TrivaController.h"
/*
#include <wx/wxprec.h>
#include <wx/wx.h>
#include "reader/TrivaPajeReader.h"
#include <vector>
*/

class TrivaController;

class GUI_CombinedCounter : public AutoGUI_CombinedCounter
{
private:
	TrivaController *controller;

protected:
	wxComboBox* stateTypeListValues;
	wxTextCtrl* stateTypeWeight;

	void addStateType( wxCommandEvent& event );
	void apply( wxCommandEvent& event );
	void close( wxCommandEvent& event );
	void onClose (wxCloseEvent& event );

public:
	void setController (TrivaController *t) { controller = t; };
	GUI_CombinedCounter( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT("Combined Counter Configuration"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 500,362 ), long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );
};

#endif 
