#ifndef __DotWindow__
#define __DotWindow__

/**
@file
Subclass of DotWindowAuto, which is generated by wxFormBuilder.
*/

#include "DotWindowAuto.h"
#include "DotDraw.h"

/** Implementing DotWindowAuto */
class DotWindow : public DotWindowAuto
{
public:
	/** Constructor */
	DotWindow( wxWindow* parent );
        DotDraw *getDraw();
	void setStatusMessage (wxString message);
};

#endif // __DotWindow__
