#ifndef __SimGridWindow__
#define __SimGridWindow__

/**
@file
Subclass of SimGridWindowAuto, which is generated by wxFormBuilder.
*/

#include "SimGridWindowAuto.h"
#include "SimGridDraw.h"

/** Implementing SimGridWindowAuto */
class SimGridWindow : public SimGridWindowAuto
{
public:
	/** Constructor */
	SimGridWindow( wxWindow* parent );
        SimGridDraw *getDraw();
	void setStatusMessage (wxString message);
};

#endif // __SimGridWindow__
