include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = CheckTrace

CheckTrace_PRINCIPAL_CLASS = CheckTrace
CheckTrace_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
CheckTrace_OBJC_FILES = CheckTrace.m

include $(GNUSTEP_MAKEFILES)/bundle.make
