include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = List

List_PRINCIPAL_CLASS = List
List_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
List_OBJC_FILES = List.m

include $(GNUSTEP_MAKEFILES)/bundle.make
