include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Entropy

Entropy_PRINCIPAL_CLASS = Entropy
Entropy_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
Entropy_OBJC_FILES = Entropy.m

include $(GNUSTEP_MAKEFILES)/bundle.make
