include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Entropy

Entropy_PRINCIPAL_CLASS = Entropy
Entropy_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
Entropy_RESOURCE_FILES = Entropy.gsmarkup
Entropy_OBJC_FILES = Entropy.m Entropy+GUI.m

include $(GNUSTEP_MAKEFILES)/bundle.make
