#ifndef __NetworkTopologyWindow__
#define __NetworkTopologyWindow__

/**
@file
Subclass of NetworkTopologyWindowAuto, which is generated by wxFormBuilder.
*/

#include "NetworkTopologyWindowAuto.h"
#include "CameraManager.h"
#include "AmbientManager.h"

/** Implementing NetworkTopologyWindowAuto */
class NetworkTopologyWindow : public NetworkTopologyWindowAuto
{
private:
	id filter;
	CameraManager *cameraManager;
	AmbientManager *ambientManager;
public:
	/** Constructor */
	NetworkTopologyWindow( wxWindow* parent );
	~NetworkTopologyWindow ();
	void zoomIn();
	void zoomOut();
	void setController (id f) { filter = f; };
	void configureZoom (double pointsPerSec);
};

#endif // __NetworkTopologyWindow__
