include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = LinkView

LinkView_PRINCIPAL_CLASS = LinkView
LinkView_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
LinkView_RESOURCE_FILES = LinkView.gsmarkup
LinkView_OBJC_FILES = DrawView.m LinkView.m LinkViewNode.m LinkViewEdge.m
LinkView_GUI_LIBS = -lRenaissance

include $(GNUSTEP_MAKEFILES)/bundle.make
