#ifndef __CommunicationPatternWindow__
#define __CommunicationPatternWindow__

/**
@file
Subclass of CommunicationPatternWindowAuto, which is generated by wxFormBuilder.
*/

#include "CommunicationPatternWindowAuto.h"
#include "CameraManager.h"
#include "AmbientManager.h"

/** Implementing CommunicationPatternWindowAuto */
class CommunicationPatternWindow : public CommunicationPatternWindowAuto
{
private:
	id filter;
	CameraManager *cameraManager;
	AmbientManager *ambientManager;
public:
	/** Constructor */
	CommunicationPatternWindow( wxWindow* parent );
	~CommunicationPatternWindow ();
	void zoomIn();
	void zoomOut();
	void setController (id f) { filter = f; };
	void configureZoom (double pointsPerSec);
};

#endif // __CommunicationPatternWindow__
