#ifndef __TRIVAGUIEvents__
#define __TRIVAGUIEvents__

/**
@file
Subclass of TRIVAGUI, which is generated by wxFormBuilder.
*/

#include "TRIVAGUI.h"


/** Implementing TRIVAGUI */
class TRIVAGUIEvents : public TRIVAGUI
{
private:

protected:
	// Handlers for TRIVAGUI events.
	void loadbundle( wxCommandEvent& event );
	void exit( wxCommandEvent& event );
	void about( wxCommandEvent& event );
	
public:
	/** Constructor */
	TRIVAGUIEvents( wxWindow* parent );
	TRIVAGUIEvents( wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = wxT("TRIVA"), const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize( 600,480 ), long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL );
};

#endif // __TRIVAGUIEvents__
