include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = FDGraphView

FDGraphView_PRINCIPAL_CLASS = GraphView
FDGraphView_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
FDGraphView_RESOURCE_FILES = FDGraphView.gsmarkup FDGraphView.plist
FDGraphView_OBJC_FILES = GraphView.m DrawView.m
FDGraphView_GUI_LIBS = -lRenaissance -lTupi

include $(GNUSTEP_MAKEFILES)/bundle.make
