include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = FDGraphView

FDGraphView_PRINCIPAL_CLASS = FDGraphView
FDGraphView_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
FDGraphView_RESOURCE_FILES = FDGraphView.gsmarkup FDGraphView.plist
FDGraphView_OBJC_FILES = FDGraphView.m FDDrawView.m
FDGraphView_GUI_LIBS = -lRenaissance -lTupi

include $(GNUSTEP_MAKEFILES)/bundle.make
