include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = EntityDot

EntityDot_PRINCIPAL_CLASS = EntityDot
EntityDot_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
EntityDot_OBJC_FILES = EntityDot.m

include $(GNUSTEP_MAKEFILES)/bundle.make
