include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = Instances

Instances_PRINCIPAL_CLASS = Instances
Instances_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
Instances_OBJC_FILES = Instances.m

include $(GNUSTEP_MAKEFILES)/bundle.make
