include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = SquarifiedTreemap

SquarifiedTreemap_PRINCIPAL_CLASS = SquarifiedTreemap
SquarifiedTreemap_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
SquarifiedTreemap_RESOURCE_FILES = SquarifiedTreemap.gsmarkup
SquarifiedTreemap_OBJC_FILES = SquarifiedTreemap.m TreemapView.m
SquarifiedTreemap_GUI_LIBS = -lRenaissance

include $(GNUSTEP_MAKEFILES)/bundle.make
