include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = TypeFilter

TypeFilter_PRINCIPAL_CLASS = TypeFilter
TypeFilter_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
TypeFilter_RESOURCE_FILES = TypeFilter.gsmarkup
TypeFilter_OBJC_FILES = TypeFilter.m TypeFilter+GUI.m
TypeFilter_GUI_LIBS = -lRenaissance

include $(GNUSTEP_MAKEFILES)/bundle.make
