#ifndef __TypeFilterWindow__
#define __TypeFilterWindow__

/**
@file
Subclass of TypeFilterWindowAuto, which is generated by wxFormBuilder.
*/

#include "TypeFilter.h"
#include "TypeFilterWindowAuto.h"

/** Implementing TypeFilterWindowAuto */
class TypeFilterWindow : public TypeFilterWindowAuto
{
private:
	TypeFilter *filter;
	PajeEntityType *currentSelectedType;
	void HierarchyChanged (PajeEntityType *t, wxTreeItemId root);

public:
	/** Constructor */
	TypeFilterWindow( wxWindow* parent );
	void setController (TypeFilter *contr) { filter = contr; };
	void HierarchyChanged ();

protected:
	void selectionChanged (wxTreeEvent& event );
	void mainCheckBoxClicked( wxCommandEvent& event );
	void checkListBoxClicked( wxCommandEvent& event );
};

#endif // __TypeFilterWindow__
