/*
    This file is part of Triva.

    Triva is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    Triva is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with Triva.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef __TypeFilterWindow__
#define __TypeFilterWindow__

/**
@file
Subclass of TypeFilterWindowAuto, which is generated by wxFormBuilder.
*/

#include "TypeFilter.h"
#include "TypeFilterWindowAuto.h"

/** Implementing TypeFilterWindowAuto */
class TypeFilterWindow : public TypeFilterWindowAuto
{
private:
	TypeFilter *filter;
	PajeEntityType *currentSelectedType;
	void HierarchyChanged (PajeEntityType *t, wxTreeItemId root);

public:
	/** Constructor */
	TypeFilterWindow( wxWindow* parent );
	void setController (TypeFilter *contr) { filter = contr; };
	void HierarchyChanged ();

protected:
	void selectionChanged (wxTreeEvent& event );
	void mainCheckBoxClicked( wxCommandEvent& event );
	void checkListBoxClicked( wxCommandEvent& event );
	void regular( wxCommandEvent& event );
	void updateRegularExpr( wxCommandEvent& event );
	void checkBasedOnRegularExpr( wxCommandEvent& event );
};

#endif // __TypeFilterWindow__
