include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = AggregationBuffer

AggregationBuffer_PRINCIPAL_CLASS = AggregationBuffer
AggregationBuffer_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
AggregationBuffer_OBJC_FILES = AggregationBuffer.m

include $(GNUSTEP_MAKEFILES)/bundle.make
