include $(GNUSTEP_MAKEFILES)/common.make

BUNDLE_NAME = SpatialIntegration

SpatialIntegration_PRINCIPAL_CLASS = SpatialIntegration
SpatialIntegration_INSTALL_DIR = $(GNUSTEP_BUNDLES)/Triva
SpatialIntegration_OBJC_FILES = SpatialIntegration.m

include $(GNUSTEP_MAKEFILES)/bundle.make
